services:
  catalogo:
    build: ./catalogo
    ports:
      - "5011:5000"

  recomendar:
    build: ./recomendar
    ports:
      - "5012:5000"

  misturas:
    build: ./misturas
    ports:
      - "5013:5000"

  contraindicacoes:
    build: ./contraindicacoes
    ports:
      - "5014:5000"

  cliente:
    build: ./cliente
    ports:
      - "5015:5000"
    depends_on:
      - catalogo
      - recomendar
      - misturas
      - contraindicacoes
