version: "3.9"

services:
  catalogo:
    build: ./catalogo
    ports:
      - "5001:5000"

  recomendacoes:
    build: ./recomendacoes
    ports:
      - "5002:5000"

  misturas:
    build: ./misturas
    ports:
      - "5003:5000"

  #contraindicacoes:
    #build: ./contraindicacoes
    #ports:
     # - "5004:5000"
