version: "3.8"

services:
  catalogo:
    build: ./catalogo
    ports:
      - "${PORT_CATALOGO}:8000"

  recomendar:
    build: ./recomendar
    ports:
      - "${PORT_RECOMENDAR}:8000"

  misturas:
    build: ./misturas
    ports:
      - "${PORT_MISTURAS}:8000"

  contraindicacoes:
    build: ./contraindicacoes
    ports:
      - "${PORT_CONTRAINDICACOES}:8000"

  cliente:
    build: ./cliente
    depends_on:
      - catalogo
      - recomendar
      - misturas
      - contraindicacoes
